# This is a config for E2B sandbox template.
# You can use template ID (8b28srvn727adkxc6pky) or template name (vishwjitpatil01/v0-clone) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox.create("vishwjitpatil01/v0-clone") # Sync sandbox
# sandbox = await AsyncSandbox.create("vishwjitpatil01/v0-clone") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('vishwjitpatil01/v0-clone')

team_id = "d49baab5-3dd9-4c67-8ade-e8237088fbf1"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "vishwjitpatil01/v0-clone"
template_id = "8b28srvn727adkxc6pky"
